name=PixelFonts
version=0.1.0
author=mcer12
maintainer=mcer12
sentence=Hand crafted pixel fonts for tiny low-res displays, compatible with Adafruit GFX and extended latin.
paragraph=PixelFont is a family of AdafruitGFX compatible fonts, hand crafted for tiny low-res displays. The fonts are designed to be slender and condensed to fit as much text on a line as possible. And to also look awesome.
category=Display
url=https://github.com/mcer12/PixelFonts
architectures=*
depends=Adafruit GFX Library
includes=PixelFonts.h
